name = "IrisRegistry"
uuid = "cccb03ba-4a51-11e9-22a9-359b3e066510"
repo = "https://github.com/wrs28/IrisRegistry.git"
description = "For Iris.jl"

[packages]
b01435f3-c073-4357-a6db-57eda4d8c2d8 = { name = "ArnoldiMethodWrapper", path = "ArnoldiMethodWrapper"}
7edf5c3c-4a51-11e9-106e-0de8ad83fb01 = { name = "Iris2", path = "Iris2"}
2c9ecdf8-4a52-11e9-39a9-59d6a9787d27 = { name = "IrisBase", path = "IrisBase" }
325a41b4-4a57-11e9-029c-c5a15b674299 = { name = "IrisSpectral", path = "IrisSpectral"}
6ed6c396-4a58-11e9-1db8-19b1dcb39f34 = { name = "IrisFloquet", path = "IrisFloquet"}
e8a29fba-4a58-11e9-29ba-414d2217d7cf = { name = "IrisScattering", path = "IrisScattering"}
cb89118e-5656-11e9-34fa-4714eb8b3a0f = { name = "IrisSCPA", path = "IrisSCPA"}
a6ba56b0-5656-11e9-2bae-710ee715d732 = { name = "IrisSALT", path = "IrisSALT"}
